/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_cpp_ckbase_CKNotification */

#ifndef _Included_org_cocos2dx_cpp_ckbase_CKNotification
#define _Included_org_cocos2dx_cpp_ckbase_CKNotification
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_cpp_ckbase_CKNotification
 * Method:    dispatchRecieveNotification
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_ckbase_CKNotification_dispatchRecieveNotification
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     org_cocos2dx_cpp_ckbase_CKNotification
 * Method:    dispatchClickNotification
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_ckbase_CKNotification_dispatchClickNotification
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
