/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_ckbase_CKMessageBox */

#ifndef _Included_org_cocos2dx_ckbase_CKMessageBox
#define _Included_org_cocos2dx_ckbase_CKMessageBox
#ifdef __cplusplus
extern "C" {
#endif
#undef org_cocos2dx_ckbase_CKMessageBox_HANDLER_CREATE_DIALOG
#define org_cocos2dx_ckbase_CKMessageBox_HANDLER_CREATE_DIALOG 1L
#undef org_cocos2dx_ckbase_CKMessageBox_HANDLER_SHOW_DIALOG
#define org_cocos2dx_ckbase_CKMessageBox_HANDLER_SHOW_DIALOG 2L
#undef org_cocos2dx_ckbase_CKMessageBox_HANDLER_HIDE_DIALOG
#define org_cocos2dx_ckbase_CKMessageBox_HANDLER_HIDE_DIALOG 3L
#undef org_cocos2dx_ckbase_CKMessageBox_HANDLER_SET_DIALOG_BUTTON
#define org_cocos2dx_ckbase_CKMessageBox_HANDLER_SET_DIALOG_BUTTON 4L
/*
 * Class:     org_cocos2dx_ckbase_CKMessageBox
 * Method:    onNativeButtonClick
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_ckbase_CKMessageBox_onNativeButtonClick
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
