/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_ckbase_CKGameHelper */

#ifndef _Included_org_cocos2dx_ckbase_CKGameHelper
#define _Included_org_cocos2dx_ckbase_CKGameHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_ckbase_CKGameHelper
 * Method:    httpUtilsGetText
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cocos2dx_ckbase_CKGameHelper_httpUtilsGetText
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
